.Dd $Mdocdate$
.Dt SWP 1
.Os
.Sh NAME
.Nm swp
.Nd swap a pair of files
.Sh SYNOPSIS
.Nm
.Ar file1
.Ar file2
.Sh DESCRIPTION
.Nm
takes a pair of files and swaps them; 
.Pa file1 
becomes 
.Pa file2 
and
.Pa file2 
becomes 
.Pa file1.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, & 9 only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, & 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, & 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, & 8 only.
.\" .Sh ERRORS
.\" For sections 2, 3, & 9 only.
.\" .Sh SEE ALSO
.\".Sh STANDARDS
.\" .Sh HISTORY
.Sh AUTHORS
.Nm
was written by
.An Kyle Isom Aq Mt kyle@tyrfingr.is .
.\" .Sh CAVEATS
.\" .Sh BUGS
.Sh LICENSE
.Nm
is released under a public domain / ISC dual license. The license is
available
.Lk http://www.tyrfingr.is/licenses/LICENSE.DUAL "online" ,

